config/routes.rb
Hzqg::Application.routes.draw do

  get "home/index"
  root 'home#index'

  resources :sessions, :only => [:new, :create, :destroy]
  resources :users
  resources :products do
    member do
      get :edit_units
      get :edit_sub_products
      get :get_units
    end
  end
  resources :warehouses do
    member do
      get :edit_alert_count
      patch :update_alert_count
    end
  end
  resources :purchases
  resources :orders do
    member do
      get :new_ration
      post :create_ration
      get :rations

      get :new_shipment
      post :create_shipment
      get :shipments
    end
  end
  resources :notifications do
    collection do
      get :update_count
    end
    member do
      get :read
    end
  end
  

end

app/models/order.rb
class Order < ActiveRecord::Base

  belongs_to :user
  has_many :line_items, :dependent => :destroy
  accepts_nested_attributes_for :line_items, :allow_destroy => true

  has_many :rations, :dependent => :destroy
  has_many :shipments, :dependent => :destroy
  has_many :products, :through => :line_items

  validates :number, :presence => true

  after_create :count_elements

  scope :not_rationed, -> {where(["element_status_id <> ?", Order.element_status[:rationed]])}

  def self.status
    {
      :begin => 0,
      :end => 1,
      :return => 2,
      :close => 3
    }
  end

  def self.element_status
    {
      :not_ration => 0,
      :rationing => 1,
      :rationed => 2
    }
  end

  def self.send_status
    {
      :not_send => 0,
      :sending => 1,
      :sent => 2
    }
  end

  def status
    self.class.status.each do |status_name, status_id|
      return status_name if self.status_id == status_id
    end
  end

  self.send_status.each do |status_name, status_id|
    define_method "#{status_name}?".to_sym do
      self.send_status_id == status_id
    end
  end


  def element_status
    self.class.element_status.each do |status_name, status_id|
      return status_name if self.element_status_id == status_id
    end
  end

  def send_status
    self.class.send_status.each do |status_name, status_id|
      return status_name if self.send_status_id == status_id
    end
  end

  def count_elements
    # 各零件总需求
    self.update_need_count_elements

    # 各零件已配货
    self.update_rationed_count_elements

    # 各零件未配货
    self.update_not_ration_count_elements

    # 各产品已发货
    self.update_shipped_count_products

    # 各产品未发货
    self.update_not_shipped_count_products

    # 更新各种状态
    self.update_is_ready_status
    self.update_element_status
    self.update_send_status

    # 更新相关产品状态
    self.update_products_status
  end

  def check_need_count_elements
    $count_redis.hgetall "order_#{self.id}_need_count"
  end

  def check_not_ration_count_elements
    $count_redis.hgetall "order_#{self.id}_not_ration_count"
  end

  def check_rationed_count_elements
    $count_redis.hgetall "order_#{self.id}_rationed_count"
  end

  def check_shipped_count_products
    $count_redis.hgetall "order_#{self.id}_shipped_count"
  end

  def check_not_shipped_count_products
    $count_redis.hgetall "order_#{self.id}_not_shipped_count"
  end

  def update_need_count_elements
    $count_redis.del "order_#{self.id}_need_count"
    self.line_items.each do |line_item|
      line_item.product.need_count_elements_for_order(self.id, line_item.product_count * line_item.unit.rate)
    end
  end

  def update_rationed_count_elements
    $count_redis.del "order_#{self.id}_rationed_count"
    self.rations.each do |ration|
      ration.ration_records.each do |record|
        record.product.rationed_count_elements_for_order(self.id, record.product_count * record.unit.rate)
      end
    end
  end

  def update_not_ration_count_elements
    $count_redis.del "order_#{self.id}_not_ration_count"
    self.check_need_count_elements.each do |product_id, need_count|
      rationed_count = $count_redis.hget("order_#{self.id}_rationed_count", product_id).to_f
      count = need_count.to_f - rationed_count.to_f
      $count_redis.hset("order_#{self.id}_not_ration_count", product_id, count) if count > 0
    end
  end

  def update_is_ready_status
    self.check_not_ration_count_elements.each do |product_id, need_count|
      product = Product.find(product_id)
      self.update_attribute(:is_ready, false) and return if product.store < need_count.to_f
    end
    self.update_attribute(:is_ready, true)
  end

  def update_element_status
    if self.check_not_ration_count_elements.blank?
      self.update_attribute(:element_status_id, Order.element_status[:rationed])
    elsif self.check_rationed_count_elements.present?
      self.update_attribute(:element_status_id, Order.element_status[:rationing])
    end
  end

  def not_ration_products
    Product.where(["id in (?)", self.check_not_ration_count_elements.keys])
  end

  def update_shipped_count_products
    $count_redis.del "order_#{self.id}_shipped_count"
    self.shipments.each do |shipment|
      shipment.shipment_records.each do |record|
        $count_redis.hincrbyfloat("order_#{self.id}_shipped_count", record.product.id, record.product_count * record.unit.rate)
      end
    end
  end

  def update_not_shipped_count_products
    $count_redis.del "order_#{self.id}_not_shipped_count"
    self.line_items.each do |line_item|
      $count_redis.hincrbyfloat("order_#{self.id}_not_shipped_count", line_item.product.id, line_item.product_count * line_item.unit.rate)
    end
    self.check_shipped_count_products.each do |product_id, sent_count|
      not_shipped_count = $count_redis.hget("order_#{self.id}_not_shipped_count", product_id).to_f
      count = not_shipped_count.to_f - sent_count.to_f
      $count_redis.hset("order_#{self.id}_not_shipped_count", product_id, count) if count > 0
    end
  end

  def update_send_status
    if self.check_not_shipped_count_products.blank?
      self.update_attribute(:send_status_id, Order.send_status[:sent])
    elsif self.check_shipped_count_products.present?
      self.update_attribute(:send_status_id, Order.send_status[:sending])
    end
  end

  def update_products_status
    self.check_need_count_elements.each do |product_id, need_count|
      Product.find(product_id).count_orders
    end
  end

end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController

  before_filter :login_required

  def index
    @q = Order.search(params[:q])
    @orders = @q.result.page(params[:page]).per(10)
  end

  def new
    @order = Order.new
    @order.line_items.build
    @products = Product.last_products
  end

  def create
    @order = Order.new(order_params)
    @order.user = current_user
    if @order.save
      redirect_to order_path(@order) and return
    else
      @products = Product.last_products
      render :new
    end
  end

  def show
    @order = Order.find(params[:id])
  end

  def new_ration
    @order = Order.find(params[:id])
    @ration = @order.rations.build
    @ration.ration_records.build({:product_count => 0})
  end

  def create_ration
    @order = Order.find(params[:id])
    @ration = @order.rations.new(ration_params)
    @ration.user = current_user
    if @ration.save
      redirect_to order_path(@order) and return
    else
      render :new_ration
    end
  end

  def rations
    @order = Order.find(params[:id])
    @rations = @order.rations
  end

  def new_shipment
    @order = Order.find(params[:id])
    @shipment = @order.shipments.build
    @shipment.shipment_records.build({:product_count => 0})
  end

  def create_shipment
    @order = Order.find(params[:id])
    @shipment = @order.shipments.new(shipment_params)
    @shipment.user = current_user
    if @shipment.save
      redirect_to order_path(@order) and return
    else
      render :new_shipment
    end
  end

  def shipments
    @order = Order.find(params[:id])
    @shipments = @order.shipments
  end

  protected

  def order_params
    params.require(:order).permit(
      :number, :remark,
      :line_items_attributes => [:id, :product_id, :unit_id, :product_count, :delivery_start, :delivery_end, :remark, :_destroy]
    )
  end

  def ration_params
    params.require(:ration).permit(
      :ration_records_attributes => [:id, :product_id, :unit_id, :product_count, :_destroy]
    )
  end

  def shipment_params
    params.require(:shipment).permit(
      :shipment_records_attributes => [:id, :product_id, :unit_id, :product_count, :_destroy]
    )
  end

end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/orders/index.html.erb
<% breadcrumb :orders %>

<div class="page-header">
  <h3>订单列表</h3>
</div>

<div class="well well-sm">
  <%= search_form_for @q, :class => "form-inline" do |f| %>

    <div class="form-group">
      <%= f.label :id_eq, "ID" %>
      <%= f.search_field :id_eq, :class => "form-control" %>
    </div>

    <div class="form-group">
      <%= f.label :number_cont, "订单号" %>
      <%= f.search_field :number_cont, :class => "form-control" %>
    </div>

    <div class="form-group">
      <%= f.label :is_ready_eq, "零件缺货" %>
      <%= f.select :is_ready_eq, [["是", "false"], ["否", "true"]], {:include_blank => true}, {:class => "form-control"} %>
    </div>

    <div class="form-group">
      <%= f.label :element_status_id_eq, "配货" %>
      <%= f.select :element_status_id_eq, order_element_status_array, {:include_blank => true}, {:class => "form-control"} %>
    </div>

    <div class="form-group">
      <%= f.label :send_status_id_eq, "交货" %>
      <%= f.select :send_status_id_eq, order_send_status_array, {:include_blank => true}, {:class => "form-control"} %>
    </div>

    <div class="form-group">
      <%= f.label :status_id_eq, "订单状态" %>
      <%= f.select :status_id_eq, order_status_array, {:include_blank => true}, {:class => "form-control"} %>
    </div>

    <%= f.submit "搜索", :class => "btn btn-primary" %>
  <% end %>
</div>

<div>
  <table class="table table-hover table-condensed table-bordered">
    <thead>
      <tr>
        <th><%= sort_link(@q, :id, "ID") %></th>
        <th><%= sort_link(@q, :number, "订单号") %></th>
        <th><%= sort_link(@q, :created_at, "创建日期") %></th>
        <th><%= sort_link(@q, :is_ready, "零件缺货") %></th>
        <th><%= sort_link(@q, :element_status_id, "零件配给") %></th>
        <th><%= sort_link(@q, :send_status_id, "成品交货") %></th>
        <th><%= sort_link(@q, :status_id, "订单状态") %></th>
        <th><%= link_to "新建订单", new_order_path, :class => "btn btn-success" %></th>
      </tr>
    </thead>
    <tbody>
      <% @orders.each do |o| %>
        <tr>
          <td><%= o.id %></td>
          <td><%= link_to o.number, order_path(o) %></td>
          <td><%= short_date o.created_at %></td>
          <td><%= show_is_ready_for_order(o) %></td>
          <td><%= translate_order_element_status_name o.element_status %></td>
          <td><%= translate_order_send_status_name o.send_status %></td>
          <td><%= translate_order_status_name o.status %></td>
          <td>
            <%#= link_to "详细信息", product_path(p), :class => "btn btn-primary" %>
            <%#= link_to "删除", product_path(p), :confirm => "确定要删除？", :method => :delete, :class => "btn btn-danger btn-xs" %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
  <%= paginate @orders %>
</div>

app/views/orders/new.html.erb
<% breadcrumb :order, @order %>

<div class="page-header">
  <h3>新建订单</h3>
</div>

<div>
  <%= simple_nested_form_for @order, :html => {:class => "form-horizontal"}, :wrapper => false do |f| %>

    <div class="panel panel-default">
      <div class="panel-heading">基本信息</div>
      <div class="panel-body">
        <%= f.input :number %>
        <%= f.input :remark %>
      </div>
    </div>

    <div class="panel panel-default">
      <div class="panel-heading">产品列表</div>
      <div class="panel-body">
        <table id="edit-sub_products-list" class="table">
          <thead>
            <th>产品名称</th>
            <th>单位</th>
            <th>数量</th>
            <th>开始交货</th>
            <th>结束交货</th>
            <th>备注</th>
            <th></th>
          </thead>
          <tbody id="line_items">
            <%= f.simple_fields_for :line_items, :wrapper => false do |u| %>
              <tr class="fields hide-control-label">
                <td>
                  <%= u.input :product_id, :collection => @products, :label_method => :name, :value_method => :id, :input_html => {:class => 'sub_product_product_id'} %>
                </td>
                <td>
                  <%= u.input :unit_id, :collection => u.object.product.present? ? u.object.product.units : [], :input_html => {:class => 'sub_product_unit_id'} %>
                </td>
                <td><%= u.input :product_count %></td>
                <td><%= u.input :delivery_start, :as => :string, :input_html => {:type => "date"} %></td>
                <td><%= u.input :delivery_end, :as => :string, :input_html => {:type => "date"} %></td>
                <td><%= u.input :remark %></td>
                <td><%= u.link_to_remove "删除", :class => "btn btn-danger" %></td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
      <div class="panel-footer">
        <%= f.link_to_add "添加", :line_items, :data => { :target => "#line_items" }, :class => "btn btn-success" %>
      </div>
    </div>

    <div class="form-group">
      <div class="col-sm-offset-2 col-sm-10">
        <%= f.button :submit, :value => "保存" %>
      </div>
    </div>

  <% end %>
</div>

app/views/orders/new_ration.html.erb
<% breadcrumb :ration, @ration %>

<div class="page-header">
  <h3>配货</h3>
</div>

<%= simple_nested_form_for @ration, :url => create_ration_order_path(@order), :html => {:class => "form-horizontal"}, :wrapper => false do |f| %>

  <div class="panel panel-default">
    <div class="panel-heading">配货零件列表</div>
    <table id="edit-sub_products-list" class="table table-bordered">
      <thead>
        <tr>
          <th>产品名称</th>
          <th>产品单位</th>
          <th>数量</th>
          <th></th>
        </tr>
      </thead>
      <tbody id="ration_records">

        <%= f.simple_fields_for :ration_records, :wrapper => false do |u| %>
          <tr class="fields hide-control-label">
            <td><%= u.input :product_id, :collection => @order.not_ration_products, :label_method => :name, :value_method => :id, :input_html => {:class => 'sub_product_product_id'} %></td>
            <td><%= u.input :unit_id, :collection => u.object.product.present? ? u.object.product.units : [], :input_html => {:class => 'sub_product_unit_id'} %></td>
            <td><%= u.input :product_count %></td>
            <td><%= u.link_to_remove "删除", :class => "btn btn-danger" %></td>
          </tr>
        <% end %>

      </tbody>
    </table>
    <div class="panel-footer">
      <%= f.link_to_add "添加配货零件", :ration_records, :data => { :target => "#ration_records" }, :class => "btn btn-success" %>
    </div>
  </div>

  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <%= f.button :submit, :value => "保存" %>
    </div>
  </div>

<% end %>

app/views/orders/new_shipment.html.erb
<% #breadcrumb :ration, @ration %>

<div class="page-header">
  <h3>发货</h3>
</div>

<%= simple_nested_form_for @shipment, :url => create_shipment_order_path(@order), :html => {:class => "form-horizontal"}, :wrapper => false do |f| %>

  <div class="panel panel-default">
    <div class="panel-heading">发货产品列表</div>
    <table id="edit-sub_products-list" class="table table-bordered">
      <thead>
        <tr>
          <th>产品名称</th>
          <th>产品单位</th>
          <th>数量</th>
          <th></th>
        </tr>
      </thead>
      <tbody id="shipment_records">

        <%= f.simple_fields_for :shipment_records, :wrapper => false do |u| %>
          <tr class="fields hide-control-label">
            <td><%= u.input :product_id, :collection => @order.products, :label_method => :name, :value_method => :id, :input_html => {:class => 'sub_product_product_id'} %></td>
            <td><%= u.input :unit_id, :collection => u.object.product.present? ? u.object.product.units : [], :input_html => {:class => 'sub_product_unit_id'} %></td>
            <td><%= u.input :product_count %></td>
            <td><%= u.link_to_remove "删除", :class => "btn btn-danger" %></td>
          </tr>
        <% end %>

      </tbody>
    </table>
    <div class="panel-footer">
      <%= f.link_to_add "添加发货产品", :shipment_records, :data => { :target => "#shipment_records" }, :class => "btn btn-success" %>
    </div>
  </div>

  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <%= f.button :submit, :value => "保存" %>
    </div>
  </div>

<% end %>

app/views/orders/rations.html.erb
<% breadcrumb :rations %>

<div class="page-header">
  <h3>配货记录</h3>
</div>

<% @rations.each do |ration| %>
  <div class="panel panel-default">
    <div class="panel-heading">
      <%= short_date_time ration.created_at %> / <%= ration.user.real_name %>
    </div>
    <table class="table table-bordered">
      <thead>
        <tr>
          <th>产品名称</th>
          <th>单位</th>
          <th>数量</th>
        </tr>
      </thead>
      <tbody>
        <% ration.ration_records.each do |record| %>
          <tr>
            <td><%= link_to record.product.name, product_path(record.product) %></td>
            <td><%= record.unit.name %></td>
            <td><%= record.product_count %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
<% end %>

app/views/orders/shipments.html.erb
<% #breadcrumb :rations %>

<div class="page-header">
  <h3>发货记录</h3>
</div>

<% @shipments.each do |shipment| %>
  <div class="panel panel-default">
    <div class="panel-heading">
      <%= short_date_time shipment.created_at %> / <%= shipment.user.real_name %>
    </div>
    <table class="table table-bordered">
      <thead>
        <tr>
          <th>产品名称</th>
          <th>单位</th>
          <th>数量</th>
        </tr>
      </thead>
      <tbody>
        <% shipment.shipment_records.each do |record| %>
          <tr>
            <td><%= link_to record.product.name, product_path(record.product) %></td>
            <td><%= record.unit.name %></td>
            <td><%= record.product_count %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
<% end %>

app/views/orders/show.html.erb
<% breadcrumb :order, @order %>

<div class="page-header">
  <h3>订单详情</h3>
</div>

<div class="row">
  <div class="col-md-4">
    订单编号: <%= @order.number %>
  </div>
  <div class="col-md-4 col-md-offset-4 text-right">
    日期: <%= short_date(@order.created_at) %> / <%= @order.user.real_name %>
  </div>
</div>

<div class="row">
  <div class="col-md-2">订单状态: <%= translate_order_status_name @order.status %></div>
  <div class="col-md-2">配货状态: <%= translate_order_element_status_name @order.element_status %></div>
  <div class="col-md-2">发货状态: <%= translate_order_send_status_name @order.send_status %></div>
</div>

<div class="padding-top-10">
  <table class="table table-bordered">
    <thead>
      <tr>
        <th>货号</th>
        <th>产品名称</th>
        <th>数量</th>
        <th>盒</th>
        <th>箱</th>
        <th>交货期</th>
        <th>备注</th>
        <th>
          <%= link_to "发货", new_shipment_order_path(@order), :class => "btn btn-success" if not @order.sent? %>
          <%= link_to "发货纪录", shipments_order_path(@order), :class => "btn btn-info" if not @order.not_send? %>
        </th>
      </tr>
    </thead>
    <tbody>
      <% @order.line_items.each do |line_item| %>
        <tr>
          <td><%= line_item.product.core_product.number %></td>
          <td><%= line_item.product.core_product.name %></td>
          <td><%= line_item_product_count line_item %></td>
          <td></td>
          <td></td>
          <td><%= line_item_delivery_date line_item %></td>
          <td><%= line_item.remark %></td>
          <td><%= show_product_send_status_for_order(@order.id, line_item.product_id) %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

<div class="page-header">
  <h3>库存状况 <%= show_is_ready_for_order(@order) %></h3>
</div>

<div class="padding-top-10">
  <table class="table table-hover table-condensed table-bordered">
      <thead>
        <tr>
          <th>产品名称</th>
          <th>库存数量</th>
          <th>需求数量</th>
          <th>配货数量</th>
          <th>未配货数量</th> 
          <th>
            <%= link_to "配货", new_ration_order_path(@order), :class => "btn btn-success" if @order.element_status_id < 2 %>
            <%= link_to "配货记录", rations_order_path(@order), :class => "btn btn-info" if @order.element_status_id > 0 %>
          </th>
        </tr>
      </thead>
      <tbody>
        <% @order.check_need_count_elements.each do |product_id, need_count| %>
          <% p = Product.find(product_id) %>
          <% rationed_count = product_rationed_count_for_order(@order, p) %>
          <% not_ration_count = product_not_ration_count_for_order(@order, p) %>
          <tr>
            <td><%= link_to p.name, product_path(p) %></td>
            <td><%= show_product_count(p, p.store) %></td>
            <td><%= show_product_count(p, need_count.to_f) %></td>
            <td><%= show_product_count(p, rationed_count) %></td>
            <td><%= show_product_count(p, not_ration_count) %></td>
            <td><%= show_product_status(p, p.store - not_ration_count) %></td>
          </tr>
        <% end %>
      </tbody>
  </table>
</div>