config/routes.rb
Hzqg::Application.routes.draw do

  get "home/index"
  root 'home#index'

  resources :sessions, :only => [:new, :create, :destroy]
  resources :users
  resources :products do
    member do
      get :edit_units
      get :edit_sub_products
      get :get_units
    end
  end
  resources :warehouses do
    member do
      get :edit_alert_count
      patch :update_alert_count
    end
  end
  resources :purchases
  resources :orders do
    member do
      get :new_ration
      post :create_ration
      get :rations

      get :new_shipment
      post :create_shipment
      get :shipments
    end
  end
  resources :notifications do
    collection do
      get :update_count
    end
    member do
      get :read
    end
  end
  

end

app/models/product.rb
class Product < ActiveRecord::Base

  mount_uploader :photo, ProductPhotoUploader

  has_many :units, :dependent => :destroy
  accepts_nested_attributes_for :units, :allow_destroy => true

  has_many :sub_products, :class_name => "SubProduct", :foreign_key => :parent_id, :dependent => :destroy
  accepts_nested_attributes_for :sub_products, :allow_destroy => true

  has_many :warehouse_records

  validates :name, :presence => true, :uniqueness => true
  validates :store, :presence => true

  attr_accessor :warehouse_log_remark

  scope :minimum_products, -> {where(["is_minimum is true"])}
  scope :last_products, -> {where(["is_last is true"])}

  def base_unit
    self.units.where(["is_base is true"]).first rescue nil
  end

  def core_product
    find_core_product(self)
  end

  def need_count_elements_for_order(order_id, need_count)
    if self.is_minimum
      $count_redis.hincrbyfloat("order_#{order_id}_need_count", self.id, need_count)
    else
      self.sub_products.each do |sp|
        sp.product.need_count_elements_for_order(order_id, need_count * sp.product_count * sp.unit.rate)
      end
    end
  end

  def rationed_count_elements_for_order(order_id, rationed_count)
    if self.is_minimum
      $count_redis.hincrbyfloat("order_#{order_id}_rationed_count", self.id, rationed_count)
    else
      self.sub_products.each do |sp|
        sp.product.rationed_count_elements_for_order(order_id, rationed_count * sp.product_count * sp.unit.rate)
      end
    end
  end

  def count_orders
    $count_redis.del "product_#{self.id}_need_count"
    Order.not_rationed.each do |order|
      need_count = $count_redis.hget("order_#{order.id}_not_ration_count", self.id).to_f
      $count_redis.hincrbyfloat("product_#{self.id}_need_count", order.id, need_count) if need_count > 0
    end
    self.update_out_of_stock_status
    self.update_low_status
  end

  def check_count_orders
    $count_redis.hgetall "product_#{self.id}_need_count"
  end

  def update_out_of_stock_status
    total_count = 0
    self.check_count_orders.each do |order_id, need_count|
      total_count += need_count.to_f
    end
    self.update_attribute(:is_out_of_stock, total_count.to_f > self.store.to_f)
  end

  def update_low_status
    self.update_attribute(:is_low, self.alert_count.to_f > self.store.to_f)
  end

  protected

  def find_core_product(p)
    return p if p.is_core
    p.sub_products.each do |sp|
      cp = find_core_product(sp.product)
      return cp if cp.present?
    end
    nil
  end

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

  before_filter :login_required

  def index
    @q = Product.search(params[:q])
    @products = @q.result.page(params[:page]).per(10)
  end

  def show
    @product = Product.find(params[:id])
  end

  def new
    @product = Product.new
  end

  def create
    @product = Product.new(product_params)
    if @product.save
      redirect_to product_path(@product) and return
    else
      render :new
    end
  end

  def edit
    @product = Product.find(params[:id])
  end

  def edit_units
    @product = Product.find(params[:id])
    @product.units.build({:is_default => true, :is_base => true, :rate => 1.0}) if @product.units.blank?
  end

  def edit_sub_products
    @product = Product.find(params[:id])
    redirect_to product_path(@product) and return if @product.is_minimum
    @products = Product.all
    @product.sub_products.build({:product_count => 0}) if @product.sub_products.blank?
  end

  def update
    @product = Product.find(params[:id])
    if @product.update_attributes(product_params)
      redirect_to product_path(@product) and return 
    else
      if params[:product][:units_attributes].present?
        render :edit_units
      elsif params[:product][:sub_products_attributes].present?
        @products = Product.all
        render :edit_sub_products
      else
        render :edit
      end
    end
  end

  def destroy
    @product = Product.find(params[:id])
    @product.destroy
    redirect_to products_path and return
  end

  def get_units
    @product = Product.find(params[:id])
    @units = @product.units
    render :json => @units.to_json and return
  end

  protected

  def product_params
    params.require(:product).permit(
      :number, :name, :photo, :is_minimum, :is_last, :is_core, 
      :units_attributes => [:id, :name, :is_default, :is_base, :rate, :_destroy],
      :sub_products_attributes => [:id, :product_id, :unit_id, :product_count, :_destroy]
    )
  end

end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_product_info_form.html.erb
<%= f.input :number %>
<%= f.input :name %>
<%= f.input :photo, :as => :file %>
<%= f.input :is_minimum %>
<%= f.input :is_last %>
<%= f.input :is_core %>

app/views/products/edit.html.erb
<% breadcrumb :edit_product, @product %>

<div class="page-header">
  <h3>编辑产品</h3>
</div>

<%= simple_nested_form_for @product, :html => {:class => "form-horizontal"}, :wrapper => false do |f| %>

  <div class="panel panel-default">
    <div class="panel-heading">产品信息</div>
    <div class="panel-body">
      <%= render "products/product_info_form", :f => f %>
    </div>
  </div>

  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <%= f.button :submit, :value => "保存" %>
    </div>
  </div>
<% end %>

app/views/products/edit_sub_products.html.erb
<% breadcrumb :edit_product, @product %>

<div class="page-header">
  <h3>编辑产品组件(<%= @product.name %>)</h3>
</div>

<%= simple_nested_form_for @product, :html => {:class => "form-horizontal"}, :wrapper => false do |f| %>

  <div class="panel panel-default">
    <div class="panel-heading">产品组件列表</div>
    <table id="edit-sub_products-list" class="table table-hover table-condensed table-bordered">
      <thead>
        <tr>
          <th>产品名称</th>
          <th>产品单位</th>
          <th>数量</th>
          <th></th>
        </tr>
      </thead>
      <tbody id="sub_products">

        <%= f.simple_fields_for :sub_products, :wrapper => false do |u| %>
          <tr class="fields hide-control-label">
            <td><%= u.input :product_id, :collection => @products, :label_method => :name, :value_method => :id, :input_html => {:class => 'sub_product_product_id'} %></td>
            <td><%= u.input :unit_id, :collection => u.object.product.present? ? u.object.product.units : [], :input_html => {:class => 'sub_product_unit_id'} %></td>
            <td><%= u.input :product_count %></td>
            <td><%= u.link_to_remove "删除", :class => "btn btn-danger" %></td>
          </tr>
        <% end %>

      </tbody>
    </table>
    <div class="panel-footer">
      <%= f.link_to_add "添加新组件", :sub_products, :data => { :target => "#sub_products" }, :class => "btn btn-success" %>
    </div>
  </div>

  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <%= f.button :submit, :value => "保存" %>
    </div>
  </div>
<% end %>

app/views/products/edit_units.html.erb
<% breadcrumb :edit_product, @product %>

<div class="page-header">
  <h3>编辑产品单位(<%= @product.name %>)</h3>
</div>

<%= simple_nested_form_for @product, :html => {:class => "form-horizontal"}, :wrapper => false do |f| %>

  <div class="panel panel-default">
    <div class="panel-heading">产品单位列表</div>
    <table id="edit-units-list" class="table table-hover table-condensed table-bordered">
      <thead>
        <tr>
          <th>单位名称</th>
          <th>默认单位</th>
          <th>基本单位</th>
          <th>换算率</th>
          <th></th>
        </tr>
      </thead>
      <tbody id="units">

        <%= f.simple_fields_for :units, :wrapper => false do |u| %>
          <tr class="fields hide-control-label">
            <td><%= u.input :name %></td>
            <td><%= u.input :is_default, :input_html => {:class => "unit_is_default"} %></td>
            <td><%= u.input :is_base, :input_html => {:class => "unit_is_base"} %></td>
            <td><%= u.input :rate, :input_html => {:class => "unit_rate"} %></td>
            <td><%= u.link_to_remove "删除", :class => "btn btn-danger" %></td>
          </tr>
        <% end %>

      </tbody>
    </table>
    <div class="panel-footer">
      <%= f.link_to_add "添加新单位", :units, :data => { :target => "#units" }, :class => "btn btn-success" %>
    </div>
  </div>

  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <%= f.button :submit, :value => "保存" %>
    </div>
  </div>
<% end %>

app/views/products/index.html.erb
<% breadcrumb :products %>

<div class="page-header">
  <h3>产品列表</h3>
</div>

<div class="well well-sm">
  <%= search_form_for @q, :class => "form-inline" do |f| %>

    <div class="form-group">
      <%= f.label :id_eq, "ID" %>
      <%= f.search_field :id_eq, :class => "form-control" %>
    </div>

    <div class="form-group">
      <%= f.label :number_cont, "货号" %>
      <%= f.search_field :number_cont, :class => "form-control" %>
    </div>

    <div class="form-group">
      <%= f.label :name_cont, "产品名称" %>
      <%= f.search_field :name_cont, :class => "form-control" %>
    </div>

    <div class="form-group">
      <%= f.label :is_minimum_eq, "基础零件" %>
      <%= f.select :is_minimum_eq, [["是", "true"], ["否", "false"]], {:include_blank => true}, {:class => "form-control"} %>
    </div>

    <div class="form-group">
      <%= f.label :is_last_eq, "最终产品" %>
      <%= f.select :is_last_eq, [["是", "true"], ["否", "false"]], {:include_blank => true}, {:class => "form-control"} %>
    </div>

    <div class="form-group">
      <%= f.label :is_core_eq, "核心产品" %>
      <%= f.select :is_core_eq, [["是", "true"], ["否", "false"]], {:include_blank => true}, {:class => "form-control"} %>
    </div>

    <%= f.submit "搜索", :class => "btn btn-primary" %>
  <% end %>
</div>

<div>
  <table class="table table-hover table-condensed table-bordered">
    <thead>
      <tr>
        <th><%= sort_link(@q, :id, "ID") %></th>
        <th><%= sort_link(@q, :number, "货号") %></th>
        <th><%= sort_link(@q, :name, "名称") %></th>
        <th>图像</th>
        <th><%= sort_link(@q, :is_minimum, "基础零件") %></th>
        <th><%= sort_link(@q, :is_last, "最终产品") %></th>
        <th><%= sort_link(@q, :is_core, "核心产品") %></th>
        <th><%= link_to "新建产品", new_product_path, :class => "btn btn-success" %></th>
      </tr>
    </thead>
    <tbody>
      <% @products.each do |p| %>
        <tr>
          <td><%= p.id %></td>
          <td><%= p.number %></td>
          <td><%= link_to p.name, product_path(p) %></td>
          <td><%= image_tag p.photo_url if p.photo %></td>
          <td><%= show_boolean_with_checkbox_for_all p.is_minimum %></td>
          <td><%= show_boolean_with_checkbox_for_all p.is_last %></td>
          <td><%= show_boolean_with_checkbox_for_all p.is_core %></td>
          <td>
            <%#= link_to "详细信息", product_path(p), :class => "btn btn-primary" %>
            <%#= link_to "删除", product_path(p), :confirm => "确定要删除？", :method => :delete, :class => "btn btn-danger btn-xs" %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
  <%= paginate @products %>
</div>

app/views/products/new.html.erb
<% breadcrumb :product, @product %>

<div class="page-header">
  <h3>新建产品</h3>
</div>

<%= simple_form_for @product, :html => {:class => "form-horizontal"} do |f| %>
  
  <%= render "products/product_info_form", :f => f %>

  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <%= f.button :submit, :value => "保存" %>
    </div>
  </div>
<% end %>

app/views/products/show.html.erb
<% breadcrumb :product, @product %>

<div class="page-header">
  <h3>产品信息</h3>
</div>

<div class="">
  <div class="panel panel-default">
    <div class="panel-heading">基本信息</div>
    <table class="table table-hover table-condensed table-bordered">
      <tr>
        <td>ID</td>
        <td><%= @product.id %></td>
      </tr>
      <tr>
        <td>货号</td>
        <td><%= @product.number %></td>
      </tr>
      <tr>
        <td>名称</td>
        <td><%= @product.name %></td>
      </tr>
      <tr>
        <td>图片</td>
        <td><%= image_tag @product.photo_url if @product.photo.present? %></td>
      </tr>
      <tr>
        <td>基础零件</td>
        <td><%= show_boolean_with_text @product.is_minimum %></td>
      </tr>
      <tr>
        <td>最终产品</td>
        <td><%= show_boolean_with_text @product.is_last %></td>
      </tr>
      <tr>
        <td>核心产品</td>
        <td><%= show_boolean_with_text @product.is_core %></td>
      </tr>
    </table>
    <div class="panel-footer">
      <%= link_to "编辑", edit_product_path(@product), :class => "btn btn-primary" %>
    </div>
  </div>
</div>

<div class="">
  <div class="panel panel-default">
    <div class="panel-heading">计量单位</div>
    <table class="table table-hover table-condensed table-bordered">
      <thead>
        <tr>
          <th>#</th>
          <th>单位名称</th>
          <th>默认单位</th>
          <th>基本单位</th>
          <th>换算率</th>
        </tr>
      </thead>
      <tbody>
      <% @product.units.each_with_index do |u, i| %>
        <tr>
          <td><%= i + 1 %></td>
          <td><%= u.name %></td>
          <td><%= show_boolean_with_checkbox_for_yes(u.is_default) %></td>
          <td><%= show_boolean_with_checkbox_for_yes(u.is_base) %></td>
          <td><%= u.rate %></td>
        </tr>
      <% end %>
      </tbody>
    </table>
    <div class="panel-footer">
      <%= link_to "编辑", edit_units_product_path(@product), :class => "btn btn-primary" %>
    </div>
  </div>
</div>

<% if not @product.is_minimum %>
<div class="">
  <div class="panel panel-default">
    <div class="panel-heading">组件信息</div>
    <table class="table table-hover table-condensed table-bordered">
      <thead>
        <tr>
          <th>#</th>
          <th>产品名称</th>
          <th>产品单位</th>
          <th>数量</th>
        </tr>
      </thead>
      <tbody>
      <% @product.sub_products.each_with_index do |s, i| %>
        <tr>
          <td><%= i + 1 %></td>
          <td><%= link_to s.product.name, product_path(s.product) %></td>
          <td><%= s.unit.name %></td>
          <td><%= s.product_count %></td>
        </tr>
      <% end %>
      </tbody>
    </table>
    <div class="panel-footer">
      <%= link_to "编辑", edit_sub_products_product_path(@product), :class => "btn btn-primary" %>
    </div>
  </div>
</div>
<% end %>