config/routes.rb
Hzqg::Application.routes.draw do

  get "home/index"
  root 'home#index'

  resources :sessions, :only => [:new, :create, :destroy]
  resources :users
  resources :products do
    member do
      get :edit_units
      get :edit_sub_products
      get :get_units
    end
  end
  resources :warehouses do
    member do
      get :edit_alert_count
      patch :update_alert_count
    end
  end
  resources :purchases
  resources :orders do
    member do
      get :new_ration
      post :create_ration
      get :rations

      get :new_shipment
      post :create_shipment
      get :shipments
    end
  end
  resources :notifications do
    collection do
      get :update_count
    end
    member do
      get :read
    end
  end
  

end

app/controllers/warehouses_controller.rb
class WarehousesController < ApplicationController

  before_filter :login_required

  def index
    @q = Product.minimum_products.search(params[:q])
    @products = @q.result.page(params[:page]).per(10)
  end

  def show
    @product = Product.find(params[:id])
  end

  def edit
    @product = Product.find(params[:id])
  end

  def update
    @product = Product.find(params[:id])
    old_store = @product.store
    if @product.update_attributes(warehouse_params)
      new_store = @product.store
      if old_store != new_store      
        WarehouseRecord.create({
          :user_id => current_user.id,
          :product_id => @product.id,
          :old_store => old_store,
          :new_store => new_store,
          :remark => @product.warehouse_log_remark
        })
      end
      redirect_to warehouses_path and return
    else
      render :edit
    end
  end

  def edit_alert_count
    @product = Product.find(params[:id])
  end

  def update_alert_count
    @product = Product.find(params[:id])
    if @product.update_attributes(warehouse_alert_params)
      @product.update_low_status # 更新预警状态
      redirect_to warehouses_path and return
    else
      render :edit_alert_count
    end
  end

  protected

  def warehouse_params
    params.require(:product).permit(:store, :warehouse_log_remark)
  end

  def warehouse_alert_params
    params.require(:product).permit(:alert_count)
  end
end

app/helpers/warehouses_helper.rb
module WarehousesHelper
end

app/views/warehouses/edit.html.erb
<% breadcrumb :warehouse, @product %>

<div class="page-header">
  <h3>修正库存</h3>
</div>

<%= simple_form_for @product, :url => warehouse_path(@product), :html => {:class => "form-horizontal"} do |f| %>
  <%= f.input :store %>
  <%= f.input :warehouse_log_remark, :as => :text %>
  
  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <%= f.button :submit, :value => "保存" %>
    </div>
  </div>
<% end %>

app/views/warehouses/edit_alert_count.html.erb
<% breadcrumb :warehouse, @product %>

<div class="page-header">
  <h3>设置库存预警</h3>
</div>

<%= simple_form_for @product, :url => update_alert_count_warehouse_path(@product), :html => {:class => "form-horizontal"} do |f| %>
  <%= f.input :alert_count %>
  
  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <%= f.button :submit, :value => "保存" %>
    </div>
  </div>
<% end %>

app/views/warehouses/index.html.erb
<% breadcrumb :warehouses %>

<div class="page-header">
  <h3>库存列表</h3>
</div>

<div class="well well-sm">
  <%= search_form_for @q, :url => warehouses_path, :class => "form-inline" do |f| %>

    <div class="form-group">
      <%= f.label :id_eq, "ID" %>
      <%= f.search_field :id_eq, :class => "form-control" %>
    </div>

    <div class="form-group">
      <%= f.label :name_cont, "产品名称" %>
      <%= f.search_field :name_cont, :class => "form-control" %>
    </div>

    <div class="form-group">
      <%= f.label :is_low_eq, "预警" %>
      <%= f.select :is_low_eq, [["是", "true"], ["否", "false"]], {:include_blank => true}, {:class => "form-control"} %>
    </div>

    <div class="form-group">
      <%= f.label :is_out_of_stock_eq, "缺货" %>
      <%= f.select :is_out_of_stock_eq, [["是", "true"], ["否", "false"]], {:include_blank => true}, {:class => "form-control"} %>
    </div>

    <%= f.submit "搜索", :class => "btn btn-primary" %>
  <% end %>
</div>

<div>
  <table class="table table-hover table-condensed table-bordered">
    <thead>
      <tr>
        <th><%= sort_link(@q, :id, "ID") %></th> 
        <th><%= sort_link(@q, :name, "产品名称") %></th>
        <th>图像</th>
        <th>单位</th>
        <th>库存数量</th>
        <th>预警数量</th>
        <th>预警</th>
        <th>缺货</th>
        <th>需求汇总</th>
        <th>
          <%= link_to "进货", new_purchase_path, :class => "btn btn-success" %>
          <%= link_to "进货记录", purchases_path, :class => "btn btn-info" %>
        </th>
      </tr>
    </thead>
    <tbody>
      <% @products.each do |p| %>
        <tr>
          <td><%= p.id %></td>
          <td><%= link_to p.name, product_path(p) %></td>
          <td><%= image_tag p.photo_url if p.photo %></td>
          <td><%= p.base_unit.name if p.base_unit %></td>
          <td><%= p.store %></td>
          <td><%= p.alert_count %></td>
          <td><%= show_low_status p %></td>
          <td><%= show_out_of_stock_status p %></td>
          <td><%= show_total p %></td>
          <td>
            <%= link_to "修正库存数量", edit_warehouse_path(p), :class => "btn btn-warning btn-xs" %>
            <%= link_to "设置库存预警", edit_alert_count_warehouse_path(p), :class => "btn btn-primary btn-xs" %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
  <%= paginate @products %>
</div>